name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4  # Updated to v4 to support Node.js 20
        with:
          submodules: true
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3  # Updated to v3 to support Node.js 20
        with:
          hugo-version: '0.110.0'

      - name: Cache Hugo Modules
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/hugo
            ./resources
          key: ${{ runner.os }}-hugo-${{ hashFiles('**/config.toml') }}
          restore-keys: ${{ runner.os }}-hugo-

      - name: Lint
        run: hugo lint

      - name: Build
        run: hugo --minify

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4  # This action already supports Node.js 20
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

